# 验证码配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
spring:
  thymeleaf:
    cache: false
redisCache:
  expire: 50400
  keyPrefix: sso_cache
redisSession:
  expire: 50400
  keyPrefix: sso_session
oauth2:
  expire:
    code: 180
    token: 21600
    refreshToken: 604800
  login:
    mutex: false
  user:
    autoCreate: false
  token:
    sm4key: 143be1ae6ee10b048f7e441cec2a9803
wechat:
  miniapp:
    appId: wx*************4a3
    secret: a6***************efa227
gitee:
  clientId: a83ea66522fef5f382c6aaffa875c7e87b21d3933277c44a326cd3407fc0b651
  clientSecret: 3ebdce2afcb4a7df9b16355f60d898d452f4d9cf8ad1ab8279bb3bb465e614db
  redirectUri: http://localhost:5186/giteeOauth2
github:
  clientId: Ov23li7oH0Djw3ZEJCoJ
  clientSecret: ada9a510b3bde542e7510142f07d32a5f6bed131
  redirectUri: http://localhost:5186/githubOauth2